
      ame: Flask App CI

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirments.txt  # Install dependencies from requirements.txt

    - name: Run tests
      run: |
        pytest tests/test_app.py  # Run tests located in the 'tests' folder

    - name: Check pytest version (Optional)
      run: |
        pytest --version  # Verify pytest is installed and working
