name: Flask App CI/CD

on:
  push:
    branches:
      - main 
  pull_request:
    

jobs:
  build:
    runs-on: ubuntu-latest  # The environment where the job will run (Ubuntu)

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python (Python 3.8)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Specify the Python version you want

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          

      
